apiVersion: v1
kind: Pod
metadata:
  name: database-noticias
  labels:
    app: database-noticias
spec:
  containers:
  - name: database-noticias
    image: aluracursos/mysql-db:1
    ports:
      - containerPort: 3306
    envFrom:
      - configMapRef:
          name: configmap-db
   
